### ISSUE TITLE
Support Python 2.7.x

### ISSUE THREAD

**Issue by evandrix** [Snaipe/python-rst2ansi#1]
I came across this from HN, and it looked decent enough to want to give it a go, but alas

```
$ sudo pip install -U rst2ansi
Collecting rst2ansi
  Downloading rst2ansi-0.1.3.tar.gz
    Complete output from command python setup.py egg_info:
    This module is not supported on versions lower than python 3.3, sorry !
    Your version of python is 2.7.11, try installing it with a more recent version.
    ----------------------------------------
```

oh well, looks like my last visit here then

**Comment by Snaipe** [comment]
Unless you are [living in the past](https://wiki.python.org/moin/Python2orPython3#What_are_the_differences.3F), I see no reason to address an issue that is nontrivial to fix, and even less so if the reporter is condescending.

There are a number of factors that makes backporting to python < 3.3 hard, and on the top of my head almost all of them are additions to the standard modules (e.g. `shutil.get_terminal_size`) -- if the backport only needed me to use `unicode` instead of `str` or do other easy syntactic changes, I would have considered it, but it does not.

I would suggest installing python 3.3 or later, then install the module with `sudo pip3 install -U rst2ansi`.
